spring:
  datasource:
    url: jdbc:mysql://xxx:3306/iflow?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: xxx
    password: xxx
logging:
  level:
   com.wolwo.iflow.infra.mapper: debug

debug: true
